{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DadosFinanceiros\",\"MedidasIndicadoresFinanceiros\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "53bb969d-ed47-4d91-982c-e716efccf829",
        "fromColumn": "Data",
        "fromTable": "DadosFinanceiros",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_31ff3601-d946-4c9a-bbd6-156834c4251a"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DadosFinanceiros",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "312476a8-35e4-4984-9d1a-8ce2c4dfece5",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          },
          {
            "name": "Componente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f7cd344-0cc5-4fca-9ed1-5c56eff0edb1",
            "sourceColumn": "Componente",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9bac12ca-063f-40dc-a92a-2c2b80093d2a",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_31ff3601-d946-4c9a-bbd6-156834c4251a"
                },
                "isDefault": true,
                "relationship": "53bb969d-ed47-4d91-982c-e716efccf829"
              }
            ]
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "219d9271-71cf-46a2-abc0-99298f3f2f0f",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "33a1a1db-8acf-4f32-943d-ce91e7734fcc",
        "partitions": [
          {
            "name": "DadosFinanceiros",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\bianq\\OneDrive\\Documentos\\Power BI Desktop\\DadosFinanceiros\\DadosFinanceiros.xlsx\"), null, true),",
                "    DadosFinanceiros_Sheet = Fonte{[Item=\"DadosFinanceiros\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(DadosFinanceiros_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}, {\"Column25\", type text}, {\"Column26\", type text}, {\"Column27\", type text}, {\"Column28\", type text}, {\"Column29\", type text}, {\"Column30\", type text}, {\"Column31\", type text}, {\"Column32\", type text}, {\"Column33\", type text}, {\"Column34\", type text}, {\"Column35\", type text}, {\"Column36\", type text}, {\"Column37\", type text}, {\"Column38\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Tipo\", type text}, {\"Componente\", type text}, {\"01/01/2019\", Int64.Type}, {\"01/02/2019\", type number}, {\"01/03/2019\", type number}, {\"01/04/2019\", Int64.Type}, {\"01/05/2019\", type number}, {\"01/06/2019\", Int64.Type}, {\"01/07/2019\", Int64.Type}, {\"01/08/2019\", Int64.Type}, {\"01/09/2019\", Int64.Type}, {\"01/10/2019\", Int64.Type}, {\"01/11/2019\", Int64.Type}, {\"01/12/2019\", Int64.Type}, {\"01/01/2020\", Int64.Type}, {\"01/02/2020\", Int64.Type}, {\"01/03/2020\", Int64.Type}, {\"01/04/2020\", Int64.Type}, {\"01/05/2020\", Int64.Type}, {\"01/06/2020\", Int64.Type}, {\"01/07/2020\", Int64.Type}, {\"01/08/2020\", Int64.Type}, {\"01/09/2020\", Int64.Type}, {\"01/10/2020\", Int64.Type}, {\"01/11/2020\", Int64.Type}, {\"01/12/2020\", Int64.Type}, {\"01/01/2022\", Int64.Type}, {\"01/02/2022\", Int64.Type}, {\"01/03/2022\", Int64.Type}, {\"01/04/2022\", Int64.Type}, {\"01/05/2022\", Int64.Type}, {\"01/06/2022\", Int64.Type}, {\"01/07/2022\", Int64.Type}, {\"01/08/2022\", Int64.Type}, {\"01/09/2022\", Int64.Type}, {\"01/10/2022\", Int64.Type}, {\"01/11/2022\", Int64.Type}, {\"01/12/2022\", Int64.Type}}),",
                "    #\"Tabela Transposta\" = Table.UnpivotOtherColumns(#\"Tipo Alterado1\",{\"Tipo\", \"Componente\"}, \"Data\", \"Valor\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Tabela Transposta\",{{\"Data\", type date}, {\"Componente\", type text}}),",
                "    #\"Tipo Alterado com Localidade\" = Table.TransformColumnTypes(#\"Tipo Alterado2\", {{\"Data\", type date}}, \"pt-BR\")",
                "in",
                "    #\"Tipo Alterado com Localidade\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_61bf573e-ec18-4f85-9e5f-5c27951cd6a4",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "46af8988-a339-4992-9493-49ac41771b15",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "45f6b2b1-09e1-43fd-9415-04e443764614",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5dd3b263-e5b5-462d-97d4-05bfbd07ea02",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0be8ab28-7996-46e2-958f-71f5edd7d036",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "349449b7-c4f6-4310-bf93-4ef479ce4317",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "de571e9e-5117-4fcf-9a63-0a48af104107",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5719c213-3ef6-4b80-9aca-f5b0e8168b79",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6f0bd1fb-141f-45e7-8733-602d013fcc61",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "a5b7d44f-107e-4b8e-988e-4c1d46f53ee8",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "61540852-c5ad-4e09-9118-d57b3db4b29c",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "b97aac0e-1ca2-433f-91b2-88c047c8194f",
                "ordinal": 3
              }
            ],
            "lineageTag": "a6211132-aa88-4336-9045-07f5023b6314"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "22fb95b3-55fd-4c14-a97c-4ec5b4d2050f",
        "partitions": [
          {
            "name": "DateTableTemplate_61bf573e-ec18-4f85-9e5f-5c27951cd6a4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_31ff3601-d946-4c9a-bbd6-156834c4251a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0f2eb981-20e5-45c0-942c-730e886fc263",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bb7546c3-3dc9-40f2-a8e8-7e44fddffc3c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d1bf3a78-6c02-4ef7-8c4b-a81bdce1150c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ee4995d2-cb7d-4e2a-ba96-bb4675704d15",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "01a20df4-7388-46f5-9c9a-2e007e48a481",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "158dec87-e543-46a2-b4c3-18fa72017af0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "aaf8eaef-e7d7-4c36-8215-7e3744c37f90",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d6c7aa8a-8bf0-4dac-94c9-b70b21df58eb",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "a3c8bf48-540c-46bd-9a06-3c25c884879f",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "33ad5999-f41c-49bc-93ad-e101e39a3286",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e9497429-8322-4c50-8cb6-568fe1958b7c",
                "ordinal": 3
              }
            ],
            "lineageTag": "14ce1eb6-55b2-49ac-9810-19abcac13a35"
          }
        ],
        "isHidden": true,
        "lineageTag": "00ec96c5-176d-4f38-a85e-7d4aa4f53010",
        "partitions": [
          {
            "name": "LocalDateTable_31ff3601-d946-4c9a-bbd6-156834c4251a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DadosFinanceiros'[Data])), 1, 1), Date(Year(MAX('DadosFinanceiros'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "MedidasIndicadoresFinanceiros",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "12f8ac3f-8185-4438-8321-2453f0ac2435",
        "measures": [
          {
            "name": "TotalReceitas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = \"Receitas\")",
            "lineageTag": "dcd55c7c-9a87-47da-895f-97e07846225e"
          },
          {
            "name": "TotalDespesas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = \"Despesas\")",
            "lineageTag": "2c8fda92-ff72-406d-a89f-33676abbb408"
          },
          {
            "name": "Lucro",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[TotalReceitas] - [TotalDespesas]",
            "lineageTag": "541a858d-2629-4ef0-a165-d14380de0598"
          },
          {
            "name": "MargemLucro",
            "expression": "DIVIDE([Lucro], [TotalReceitas], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e5ca28a6-b670-447a-956c-f3f7ab637559"
          }
        ],
        "partitions": [
          {
            "name": "MedidasIndicadoresFinanceiros",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}